#!/usr/bin/env node
import { spawnSync } from 'node:child_process';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const guard = resolve(dirname(fileURLToPath(import.meta.url)), '../orchestration/pre-bash-guard.mjs');

const tests = [
  ['git push' + ' -f origin feat/thing', 2, 'short -f blocked'],
  ['git push' + ' -fu origin feat/thing', 2, 'grouped -fu blocked'],
  ['git push --force-with-lease origin feat/thing', 0, '--force-with-lease allowed'],
  ['git push origin main', 0, 'direct main push allowed'],
  ['git push --force-with-lease origin main', 2, '--force-with-lease to main blocked'],
  ['git push --force-with-lease origin HEAD:refs/heads/main', 2, '--force-with-lease HEAD to main blocked'],
  ['rm -f' + ' -r src', 2, 'split flags blocked'],
  ['rm -fr public/', 2, 'rm -fr blocked'],
  ['rm --recursive --force "src"', 2, 'long-option rm blocked'],
  ['rm src/', 2, 'bare rm of protected dir blocked'],
  ['rm -rf src-old', 0, 'src-old not blocked'],
  ['git push origin main-fix', 0, 'main-fix not blocked'],
  ['git push origin HEAD:main', 0, 'refspec HEAD:main allowed'],
  ['git push origin HEAD:refs/heads/main', 0, 'refspec refs/heads/main allowed'],
  ['git -c core.pager=cat push origin main', 0, 'git -c push main allowed'],
  ['git --no-pager push' + ' -f origin feat/x', 2, 'git --no-pager push -f blocked'],
  ['git -C /tmp push origin main', 0, 'git -C push main allowed'],
  ["git -c user.name='A B' push origin main", 0, 'git -c quoted value push main allowed'],
  ['rm -rf -- src', 2, 'rm -rf -- src blocked'],
  ['rm -rf -- public/', 2, 'rm -rf -- public/ blocked'],
  ['git push \'--force\' origin feat/x', 2, 'quoted --force blocked'],
  ['git push "--force" origin feat/x', 2, 'double-quoted --force blocked'],
  ['git push origin --all', 2, '--all push blocked'],
  ['git push --mirror origin', 2, '--mirror push blocked'],
  ['git push origin :main', 2, 'deletion refspec :main blocked'],
  ['git push origin :refs/heads/main', 2, 'deletion refspec :refs/heads/main blocked'],
  ['git reset -q --hard', 2, 'reset -q --hard blocked'],
  ['git push --no-verify origin feat', 2, 'push --no-verify blocked'],
  ['git merge --no-verify feat', 2, 'merge --no-verify blocked'],
  ['rm -rf /workspace/landing-page/src', 2, 'absolute path rm blocked'],
  ['rm -rf /home/user/landing-page/harness/', 2, 'absolute path rm harness blocked'],
  ['git push origin +main', 2, '+refspec force push to main blocked'],
  ['git push origin +feat/x', 2, '+refspec force push blocked'],
  ['rm -rf tmp src', 2, 'rm with protected dir as second operand blocked'],
  ['rm -rf foo public bar', 2, 'rm with protected dir as middle operand blocked'],
  ['rm -rf my-src-file', 0, 'rm of non-protected file not blocked'],
  ['git --exec-path /tmp push origin' + ' main', 0, 'git --exec-path push main allowed'],
  ['git commit -n -m test', 2, 'commit -n (short --no-verify) blocked'],
  ['git push -n origin feature', 0, 'push -n (dry-run) not blocked'],
  ['git merge -n feature', 0, 'merge -n (no-stat) not blocked'],
  ['git push origin main;echo done', 0, 'push main with semicolon allowed'],
  ['git push origin main&&echo ok', 0, 'push main with && allowed'],
  ['rm -rf src;echo done', 2, 'rm src with semicolon blocked'],
  ['git push origin main&', 0, 'push main with background & allowed'],
  ['rm -rf src>/dev/null', 2, 'rm src with redirect blocked'],
  ["git --work-tree \"/tmp/a b\" push origin main", 0, 'git --work-tree quoted push main allowed'],
  ['git --config-env user.name=MY_ENV push origin main', 0, 'git --config-env push main allowed'],
  ['echo git push origin main', 0, 'echo of git push not blocked'],
  ['echo "rm -rf src"', 0, 'echo of rm not blocked'],
  ['echo ok\ngit push origin main', 0, 'newline-separated push main allowed'],
  ['echo ok' + ' & git push origin main', 0, 'background &-separated push main allowed'],
  ['git --work-tree="/tmp/a b" push origin main', 0, 'git --opt=quoted push main allowed'],
  ['git commit -nm "msg"', 2, 'commit -nm (grouped no-verify) blocked'],
  ['git commit -nS -m msg', 2, 'commit -nS (uppercase grouped) blocked'],
  ['git push origin ma\\\nin', 0, 'escaped newline push main allowed'],
  ['env X=1 git push origin main', 0, 'env-prefixed push main allowed'],
  ['command rm -rf src', 2, 'command-prefixed rm blocked'],
  ['sudo git push origin main', 0, 'sudo-prefixed push main allowed'],
  ['FOO=1 git push origin main', 0, 'assignment-prefixed push main allowed'],
  ['FOO=1 rm -rf src', 2, 'assignment-prefixed rm blocked'],
  ['env A=1 B=2 git push origin main', 0, 'multi-env push main allowed'],
  ['echo $(git push origin main)', 0, 'command substitution push main allowed'],
  ['git push origin "main"', 0, 'quoted refspec main allowed'],
  ['rm -rf src*', 2, 'glob rm src* blocked'],
  ['git commit -m "fix -n bug"', 0, 'commit message containing -n not blocked'],
  ['git commit -n -m "fix bug"', 2, 'commit -n before -m blocked'],
  ['(git push origin main)', 0, 'subshell push main allowed'],
  ['(rm -rf src)', 2, 'subshell rm blocked'],
  ['/usr/bin/git push origin main', 0, 'absolute path git push main allowed'],
  ['/bin/rm -rf src', 2, 'absolute path rm blocked'],
  ['git commit --message "fix -n bug"', 0, 'commit --message with -n not blocked'],
  ['echo $(echo $(git push origin main))', 0, 'nested substitution push main allowed'],
  ['FOO="a b" git push origin main', 0, 'quoted assignment prefix push main allowed'],
  ['env FOO="a b" rm -rf src', 2, 'quoted env assignment rm blocked'],
  ['cat <(git push origin main)', 0, 'process substitution push main allowed'],
  ["bash -c 'git push origin main'", 0, 'bash -c push main allowed'],
  ['sh -c "rm -rf src"', 2, 'sh -c rm blocked'],
  ['eval "git push origin main"', 0, 'eval push main allowed'],
  ['env -i git push origin main', 0, 'env -i push main allowed'],
  ['sudo -u root rm -rf src', 2, 'sudo -u rm blocked'],
  ['command -- git push origin main', 0, 'command -- push main allowed'],
  ['\\git push origin main', 0, 'backslash-escaped git push main allowed'],
  ['\\rm -rf src', 2, 'backslash-escaped rm blocked'],
  ['echo "hello|rm -rf src"', 0, 'quoted separator not split'],
  ['time git push origin main', 0, 'time-wrapped push main allowed'],
  ['time rm -rf src', 2, 'time-wrapped rm blocked'],
  ['sudo -u root -n git push origin main', 0, 'sudo with multiple flags push main allowed'],
  ['env -C /tmp rm -rf src', 2, 'env -C with arg blocked'],
  ['case x in x) git push origin main ;; esac', 0, 'case arm push main allowed'],
  ["echo 'a'; git push origin main", 0, 'quote-then-separator push main allowed'],
  ['! git push origin main', 0, 'negated push main allowed'],
  ['{ git push origin main; }', 0, 'brace-grouped push main allowed'],
  ["echo '$(git push origin main)'", 0, 'single-quoted substitution not blocked'],
];

let failed = 0;
for (const [cmd, expected, desc] of tests) {
  const r = spawnSync('node', [guard], {
    input: JSON.stringify({ tool_input: { command: cmd } }),
    encoding: 'utf8',
  });
  const ok = r.status === expected;
  console.log(ok ? '  PASS' : '  FAIL', desc, `(exit: ${r.status}, expected: ${expected})`);
  if (!ok) failed++;
}
console.log(`\n${tests.length - failed} passed, ${failed} failed`);
process.exit(failed > 0 ? 1 : 0);
